### ISSUE TITLE
Unable to see the opponent choice

### ISSUE THREAD

**Issue by Dan1one** [campezzi/elm_rock_paper_scissors_lizard_spock#2]
Thanks for providing such a comprehensive framework with this fabulous game. I can already foresee it providing entertainment for people of all ages around the web.

However, I seem to feel frustrated that I don't get to see what my opponent move was. It makes me feel like if the game has been rigged to make Spock lose to a lizard every time!

I hope this gets resolved soon.

Live long and prosper.

Daniel

**Comment by campezzi** [comment]
Thanks for your enthusiastic bug report. This has been closed by [this commit](https://github.com/campezzi/elm_rock_paper_scissors_lizard_spock/commit/df0913cfa2e98b9fd7aea79811ed418d596d3f53).

Live long and prosper.
